name: Auto Build Lichee RV Debian Linux Bootable Image.
on:
  push:
    tags:
      - '*'
jobs:
  build-all-os:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Install depends
          run: sudo apt install -y qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support

        - name: Prepare
          run: |
            echo ${{runner.workspace}}
            mkdir -p lichee_rv_86
            mkdir -p lichee_rv_dock
        - name: Build
          run: |
            export DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1
            docker-compose build

        - name: Create Lichee RV Dock Image
          run: |
            export DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1
            docker-compose up dock
            ls -l lichee_rv_dock/*
        - name: Create Lichee RV 86 panel Image
          run: |
            export DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1
            docker-compose up panel
            ls -l lichee_rv_86/*
        - name: Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              lichee_rv_86/lichee_rv_86*.img.xz
              lichee_rv_dock/lichee_rv_dock*.img.xz
              README.txt
